import { useEffect, useState } from 'react';

import Posts from '../components/posts.js'

import Head from 'next/head';
import Link from 'next/link'

import styles from '../styles/index.module.css'

export default function Home (){
  const [redirectUserPage, setRedirectUserPage] = useState('/form');

  useEffect(()=>{//pega dados local
    const userLogged = JSON.parse(localStorage.getItem('Logged')) || false
    if(userLogged[0]) {
      setRedirectUserPage('/userPage')
    }else{
      setRedirectUserPage("/form")
    }
  },[])

  return (
    <div className={styles.container}>
      <Head>
        <title>Blog Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>

      <main>
        <h1>Página Inicial Blog</h1>
        <nav>
          <Link href={redirectUserPage}>
            <a >UserPage</a>
          </Link>
          <Link href="/create-post">
            <a >CreatePostPage</a>
          </Link>
        </nav>
      </main>

      <Posts />
    </div>
  );
}
