name: test workflow

on:
  repository_dispatch:
    types: [run-tests]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 📦 Install Dependencies
        run: |
          yarn install

      - name: Print client payload values
        run: 'echo "Client Payload: ${{ toJson(github.event.client_payload) }}"'

      - name: Update PR status
        uses: actions/github-script@v6
        with:
          script: |
            const { pr_number } = context.payload.client_payload;
            github.rest.issues.createComment({
              owner: 'leonardo-junior',
              repo: 'utiLive',
              issue_number: pr_number,
              body: 'E2E tests completed successfully'
            });
